# 应用名称
spring:
  application:
    name: upload
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 100MB
  redis:
    client-name: redis-test
    port: 6379
    host: 192.168.12.130
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
        max-wait: 60000
    timeout: 6000
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.12.130:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
# 应用服务 WEB 访问端口
server:
  port: 8080

upload:
  path: E:\Data\Project\upload-test\upload\
  chunkSize: 2048

